export Question from '../../components/Question'
export ResultSuccess from './ResultSuccess'
export ResultFailure from './ResultFailure'
export Questions from './Questions'
export Ranking from './Ranking'